# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose the port the server runs on
EXPOSE 3002

# Command to run the server
CMD ["node", "server/server.js"]